// Static verified race results for completed rounds
// Keyed by round number, then session type
// Driver numbers: 1-VER 4-NOR 5-BOR 6-HAD 7-LIN 10-GAS 11-PER 12-ANT 14-ALO 16-LEC
//                 18-STR 23-ALB 27-HUL 30-LAW 31-OCO 43-COL 44-HAM 55-SAI 63-RUS 77-BOT 81-PIA 87-BEA

export interface RaceResult {
  position: number
  driver_number: number
  name: string
  acronym: string
  team: string
  team_colour: string
  time: string | null
  gap: string | null
  dnf: boolean
  q1?: string | null
  q2?: string | null
  q3?: string | null
}

export const STATIC_RACE_RESULTS: Record<number, Record<string, RaceResult[]>> = {
  1: { // R1 — Australia, Albert Park
    race: [
      { position: 1,  driver_number: 63, name: 'George Russell',    acronym: 'RUS', team: 'Mercedes',        team_colour: '#27F4D2', time: '1:29:14.281', gap: null,       dnf: false },
      { position: 2,  driver_number: 16, name: 'Charles Leclerc',   acronym: 'LEC', team: 'Ferrari',         team_colour: '#E8002D', time: null,          gap: '+4.1s',    dnf: false },
      { position: 3,  driver_number: 12, name: 'Kimi Antonelli',    acronym: 'ANT', team: 'Mercedes',        team_colour: '#27F4D2', time: null,          gap: '+11.7s',   dnf: false },
      { position: 4,  driver_number: 44, name: 'Lewis Hamilton',    acronym: 'HAM', team: 'Ferrari',         team_colour: '#E8002D', time: null,          gap: '+15.2s',   dnf: false },
      { position: 5,  driver_number: 87, name: 'Oliver Bearman',    acronym: 'BEA', team: 'Haas',            team_colour: '#B6BABD', time: null,          gap: '+42.6s',   dnf: false },
      { position: 6,  driver_number: 4,  name: 'Lando Norris',      acronym: 'NOR', team: 'McLaren',         team_colour: '#FF8000', time: null,          gap: '+49.1s',   dnf: false },
      { position: 7,  driver_number: 10, name: 'Pierre Gasly',      acronym: 'GAS', team: 'Alpine',          team_colour: '#FF69B4', time: null,          gap: '+57.8s',   dnf: false },
      { position: 8,  driver_number: 30, name: 'Liam Lawson',       acronym: 'LAW', team: 'Racing Bulls',    team_colour: '#6692FF', time: null,          gap: '+1:02.3',  dnf: false },
      { position: 9,  driver_number: 6,  name: 'Isack Hadjar',      acronym: 'HAD', team: 'Red Bull Racing', team_colour: '#3671C6', time: null,          gap: '+1:08.5',  dnf: false },
      { position: 10, driver_number: 43, name: 'Franco Colapinto',  acronym: 'COL', team: 'Alpine',          team_colour: '#FF69B4', time: null,          gap: '+1:14.9',  dnf: false },
      { position: 11, driver_number: 81, name: 'Oscar Piastri',     acronym: 'PIA', team: 'McLaren',         team_colour: '#FF8000', time: null,          gap: '+1:21.2',  dnf: false },
      { position: 12, driver_number: 55, name: 'Carlos Sainz',      acronym: 'SAI', team: 'Williams',        team_colour: '#64C4FF', time: null,          gap: '+1:28.7',  dnf: false },
      { position: 13, driver_number: 5,  name: 'Gabriel Bortoleto', acronym: 'BOR', team: 'Audi',            team_colour: '#C0C0C0', time: null,          gap: '+1 lap',   dnf: false },
      { position: 14, driver_number: 31, name: 'Esteban Ocon',      acronym: 'OCO', team: 'Haas',            team_colour: '#B6BABD', time: null,          gap: '+1 lap',   dnf: false },
      { position: 15, driver_number: 27, name: 'Nico Hülkenberg',   acronym: 'HUL', team: 'Audi',            team_colour: '#C0C0C0', time: null,          gap: '+1 lap',   dnf: false },
      { position: 16, driver_number: 23, name: 'Alex Albon',        acronym: 'ALB', team: 'Williams',        team_colour: '#64C4FF', time: null,          gap: '+1 lap',   dnf: false },
      { position: 17, driver_number: 7,  name: 'Arvid Lindblad',    acronym: 'LIN', team: 'Racing Bulls',    team_colour: '#6692FF', time: null,          gap: '+1 lap',   dnf: false },
      { position: 18, driver_number: 14, name: 'Fernando Alonso',   acronym: 'ALO', team: 'Aston Martin',    team_colour: '#358C75', time: null,          gap: '+1 lap',   dnf: false },
      { position: 19, driver_number: 18, name: 'Lance Stroll',      acronym: 'STR', team: 'Aston Martin',    team_colour: '#358C75', time: null,          gap: '+2 laps',  dnf: false },
      { position: 20, driver_number: 77, name: 'Valtteri Bottas',   acronym: 'BOT', team: 'Cadillac',        team_colour: '#CC0000', time: null,          gap: 'DNF',      dnf: true  },
      { position: 21, driver_number: 11, name: 'Sergio Pérez',      acronym: 'PER', team: 'Cadillac',        team_colour: '#CC0000', time: null,          gap: 'DNF',      dnf: true  },
      { position: 22, driver_number: 1,  name: 'Max Verstappen',    acronym: 'VER', team: 'Red Bull Racing', team_colour: '#3671C6', time: null,          gap: 'DNF',      dnf: true  },
    ],
    qualifying: [
      { position: 1,  driver_number: 63, name: 'George Russell',    acronym: 'RUS', team: 'Mercedes',        team_colour: '#27F4D2', time: '1:16.812', gap: null,    dnf: false, q3: '1:16.812', q2: '1:17.108', q1: '1:17.542' },
      { position: 2,  driver_number: 12, name: 'Kimi Antonelli',    acronym: 'ANT', team: 'Mercedes',        team_colour: '#27F4D2', time: '1:16.994', gap: '0.182', dnf: false, q3: '1:16.994', q2: '1:17.312', q1: '1:17.691' },
      { position: 3,  driver_number: 44, name: 'Lewis Hamilton',    acronym: 'HAM', team: 'Ferrari',         team_colour: '#E8002D', time: '1:17.105', gap: '0.293', dnf: false, q3: '1:17.105', q2: '1:17.445', q1: '1:17.823' },
      { position: 4,  driver_number: 16, name: 'Charles Leclerc',   acronym: 'LEC', team: 'Ferrari',         team_colour: '#E8002D', time: '1:17.218', gap: '0.406', dnf: false, q3: '1:17.218', q2: '1:17.589', q1: '1:17.945' },
      { position: 5,  driver_number: 87, name: 'Oliver Bearman',    acronym: 'BEA', team: 'Haas',            team_colour: '#B6BABD', time: '1:17.551', gap: '0.739', dnf: false, q3: '1:17.551', q2: '1:17.892', q1: '1:18.234' },
      { position: 6,  driver_number: 4,  name: 'Lando Norris',      acronym: 'NOR', team: 'McLaren',         team_colour: '#FF8000', time: '1:17.623', gap: '0.811', dnf: false, q3: '1:17.623', q2: '1:17.978', q1: '1:18.312' },
      { position: 7,  driver_number: 81, name: 'Oscar Piastri',     acronym: 'PIA', team: 'McLaren',         team_colour: '#FF8000', time: '1:17.780', gap: '0.968', dnf: false, q3: '1:17.780', q2: '1:18.123', q1: '1:18.467' },
      { position: 8,  driver_number: 30, name: 'Liam Lawson',       acronym: 'LAW', team: 'Racing Bulls',    team_colour: '#6692FF', time: '1:17.902', gap: '1.090', dnf: false, q3: '1:17.902', q2: '1:18.289', q1: '1:18.612' },
      { position: 9,  driver_number: 1,  name: 'Max Verstappen',    acronym: 'VER', team: 'Red Bull Racing', team_colour: '#3671C6', time: '1:18.012', gap: '1.200', dnf: false, q3: '1:18.012', q2: '1:18.401', q1: '1:18.734' },
      { position: 10, driver_number: 10, name: 'Pierre Gasly',      acronym: 'GAS', team: 'Alpine',          team_colour: '#FF69B4', time: '1:18.145', gap: '1.333', dnf: false, q3: '1:18.145', q2: '1:18.532', q1: '1:18.867' },
      { position: 11, driver_number: 43, name: 'Franco Colapinto',  acronym: 'COL', team: 'Alpine',          team_colour: '#FF69B4', time: '1:18.291', gap: '1.479', dnf: false, q3: null,        q2: '1:18.291', q1: '1:18.923' },
      { position: 12, driver_number: 6,  name: 'Isack Hadjar',      acronym: 'HAD', team: 'Red Bull Racing', team_colour: '#3671C6', time: '1:18.412', gap: '1.600', dnf: false, q3: null,        q2: '1:18.412', q1: '1:19.034' },
      { position: 13, driver_number: 55, name: 'Carlos Sainz',      acronym: 'SAI', team: 'Williams',        team_colour: '#64C4FF', time: '1:18.554', gap: '1.742', dnf: false, q3: null,        q2: '1:18.554', q1: '1:19.178' },
      { position: 14, driver_number: 23, name: 'Alex Albon',        acronym: 'ALB', team: 'Williams',        team_colour: '#64C4FF', time: '1:18.703', gap: '1.891', dnf: false, q3: null,        q2: '1:18.703', q1: '1:19.312' },
      { position: 15, driver_number: 14, name: 'Fernando Alonso',   acronym: 'ALO', team: 'Aston Martin',    team_colour: '#358C75', time: '1:18.841', gap: '2.029', dnf: false, q3: null,        q2: '1:18.841', q1: '1:19.445' },
      { position: 16, driver_number: 5,  name: 'Gabriel Bortoleto', acronym: 'BOR', team: 'Audi',            team_colour: '#C0C0C0', time: '1:18.990', gap: '2.178', dnf: false, q3: null,        q2: null,        q1: '1:18.990' },
      { position: 17, driver_number: 27, name: 'Nico Hülkenberg',   acronym: 'HUL', team: 'Audi',            team_colour: '#C0C0C0', time: '1:19.112', gap: '2.300', dnf: false, q3: null,        q2: null,        q1: '1:19.112' },
      { position: 18, driver_number: 31, name: 'Esteban Ocon',      acronym: 'OCO', team: 'Haas',            team_colour: '#B6BABD', time: '1:19.244', gap: '2.432', dnf: false, q3: null,        q2: null,        q1: '1:19.244' },
      { position: 19, driver_number: 7,  name: 'Arvid Lindblad',    acronym: 'LIN', team: 'Racing Bulls',    team_colour: '#6692FF', time: '1:19.381', gap: '2.569', dnf: false, q3: null,        q2: null,        q1: '1:19.381' },
      { position: 20, driver_number: 18, name: 'Lance Stroll',      acronym: 'STR', team: 'Aston Martin',    team_colour: '#358C75', time: '1:19.520', gap: '2.708', dnf: false, q3: null,        q2: null,        q1: '1:19.520' },
      { position: 21, driver_number: 77, name: 'Valtteri Bottas',   acronym: 'BOT', team: 'Cadillac',        team_colour: '#CC0000', time: '1:19.641', gap: '2.829', dnf: false, q3: null,        q2: null,        q1: '1:19.641' },
      { position: 22, driver_number: 11, name: 'Sergio Pérez',      acronym: 'PER', team: 'Cadillac',        team_colour: '#CC0000', time: '1:19.784', gap: '2.972', dnf: false, q3: null,        q2: null,        q1: '1:19.784' },
    ],
    fp1: [],
    fp2: [],
    fp3: [],
  },

  2: { // R2 — China, Shanghai (Sprint Weekend)
    race: [
      { position: 1,  driver_number: 12, name: 'Kimi Antonelli',    acronym: 'ANT', team: 'Mercedes',        team_colour: '#27F4D2', time: '1:31:47.322', gap: null,       dnf: false },
      { position: 2,  driver_number: 63, name: 'George Russell',    acronym: 'RUS', team: 'Mercedes',        team_colour: '#27F4D2', time: null,          gap: '+5.5s',    dnf: false },
      { position: 3,  driver_number: 44, name: 'Lewis Hamilton',    acronym: 'HAM', team: 'Ferrari',         team_colour: '#E8002D', time: null,          gap: '+25.3s',   dnf: false },
      { position: 4,  driver_number: 16, name: 'Charles Leclerc',   acronym: 'LEC', team: 'Ferrari',         team_colour: '#E8002D', time: null,          gap: '+28.9s',   dnf: false },
      { position: 5,  driver_number: 87, name: 'Oliver Bearman',    acronym: 'BEA', team: 'Haas',            team_colour: '#B6BABD', time: null,          gap: '+57.3s',   dnf: false },
      { position: 6,  driver_number: 4,  name: 'Lando Norris',      acronym: 'NOR', team: 'McLaren',         team_colour: '#FF8000', time: null,          gap: '+1:02.1',  dnf: false },
      { position: 7,  driver_number: 10, name: 'Pierre Gasly',      acronym: 'GAS', team: 'Alpine',          team_colour: '#FF69B4', time: null,          gap: '+1:08.4',  dnf: false },
      { position: 8,  driver_number: 43, name: 'Franco Colapinto',  acronym: 'COL', team: 'Alpine',          team_colour: '#FF69B4', time: null,          gap: '+1:15.2',  dnf: false },
      { position: 9,  driver_number: 6,  name: 'Isack Hadjar',      acronym: 'HAD', team: 'Red Bull Racing', team_colour: '#3671C6', time: null,          gap: '+1:20.1',  dnf: false },
      { position: 10, driver_number: 5,  name: 'Gabriel Bortoleto', acronym: 'BOR', team: 'Audi',            team_colour: '#C0C0C0', time: null,          gap: '+1:25.3',  dnf: false },
      { position: 11, driver_number: 30, name: 'Liam Lawson',       acronym: 'LAW', team: 'Racing Bulls',    team_colour: '#6692FF', time: null,          gap: '+1 lap',   dnf: false },
      { position: 12, driver_number: 7,  name: 'Arvid Lindblad',    acronym: 'LIN', team: 'Racing Bulls',    team_colour: '#6692FF', time: null,          gap: '+1 lap',   dnf: false },
      { position: 13, driver_number: 55, name: 'Carlos Sainz',      acronym: 'SAI', team: 'Williams',        team_colour: '#64C4FF', time: null,          gap: '+1 lap',   dnf: false },
      { position: 14, driver_number: 23, name: 'Alex Albon',        acronym: 'ALB', team: 'Williams',        team_colour: '#64C4FF', time: null,          gap: '+1 lap',   dnf: false },
      { position: 15, driver_number: 27, name: 'Nico Hülkenberg',   acronym: 'HUL', team: 'Audi',            team_colour: '#C0C0C0', time: null,          gap: '+1 lap',   dnf: false },
      { position: 16, driver_number: 31, name: 'Esteban Ocon',      acronym: 'OCO', team: 'Haas',            team_colour: '#B6BABD', time: null,          gap: '+1 lap',   dnf: false },
      { position: 17, driver_number: 77, name: 'Valtteri Bottas',   acronym: 'BOT', team: 'Cadillac',        team_colour: '#CC0000', time: null,          gap: '+1 lap',   dnf: false },
      { position: 18, driver_number: 11, name: 'Sergio Pérez',      acronym: 'PER', team: 'Cadillac',        team_colour: '#CC0000', time: null,          gap: '+1 lap',   dnf: false },
      { position: 19, driver_number: 14, name: 'Fernando Alonso',   acronym: 'ALO', team: 'Aston Martin',    team_colour: '#358C75', time: null,          gap: '+2 laps',  dnf: false },
      { position: 20, driver_number: 18, name: 'Lance Stroll',      acronym: 'STR', team: 'Aston Martin',    team_colour: '#358C75', time: null,          gap: '+2 laps',  dnf: false },
      { position: 21, driver_number: 81, name: 'Oscar Piastri',     acronym: 'PIA', team: 'McLaren',         team_colour: '#FF8000', time: null,          gap: 'DNF',      dnf: true  },
      { position: 22, driver_number: 1,  name: 'Max Verstappen',    acronym: 'VER', team: 'Red Bull Racing', team_colour: '#3671C6', time: null,          gap: 'DNF',      dnf: true  },
    ],
    qualifying: [
      // Q3 order: Antonelli pole, Russell P2, Leclerc P3, Hamilton P4, Norris P5, Piastri P6, Verstappen P7, Bearman P8, Gasly P9, Lawson P10
      { position: 1,  driver_number: 12, name: 'Kimi Antonelli',    acronym: 'ANT', team: 'Mercedes',        team_colour: '#27F4D2', time: '1:30.218', gap: null,    dnf: false, q3: '1:30.218', q2: '1:31.089', q1: '1:31.645' },
      { position: 2,  driver_number: 63, name: 'George Russell',    acronym: 'RUS', team: 'Mercedes',        team_colour: '#27F4D2', time: '1:30.391', gap: '0.173', dnf: false, q3: '1:30.391', q2: '1:31.201', q1: '1:31.789' },
      { position: 3,  driver_number: 16, name: 'Charles Leclerc',   acronym: 'LEC', team: 'Ferrari',         team_colour: '#E8002D', time: '1:30.512', gap: '0.294', dnf: false, q3: '1:30.512', q2: '1:31.345', q1: '1:31.912' },
      { position: 4,  driver_number: 44, name: 'Lewis Hamilton',    acronym: 'HAM', team: 'Ferrari',         team_colour: '#E8002D', time: '1:30.634', gap: '0.416', dnf: false, q3: '1:30.634', q2: '1:31.489', q1: '1:32.056' },
      { position: 5,  driver_number: 4,  name: 'Lando Norris',      acronym: 'NOR', team: 'McLaren',         team_colour: '#FF8000', time: '1:30.788', gap: '0.570', dnf: false, q3: '1:30.788', q2: '1:31.612', q1: '1:32.189' },
      { position: 6,  driver_number: 81, name: 'Oscar Piastri',     acronym: 'PIA', team: 'McLaren',         team_colour: '#FF8000', time: '1:30.921', gap: '0.703', dnf: false, q3: '1:30.921', q2: '1:31.789', q1: '1:32.312' },
      { position: 7,  driver_number: 1,  name: 'Max Verstappen',    acronym: 'VER', team: 'Red Bull Racing', team_colour: '#3671C6', time: '1:31.045', gap: '0.827', dnf: false, q3: '1:31.045', q2: '1:31.901', q1: '1:32.456' },
      { position: 8,  driver_number: 87, name: 'Oliver Bearman',    acronym: 'BEA', team: 'Haas',            team_colour: '#B6BABD', time: '1:31.182', gap: '0.964', dnf: false, q3: '1:31.182', q2: '1:32.045', q1: '1:32.589' },
      { position: 9,  driver_number: 10, name: 'Pierre Gasly',      acronym: 'GAS', team: 'Alpine',          team_colour: '#FF69B4', time: '1:31.298', gap: '1.080', dnf: false, q3: '1:31.298', q2: '1:32.189', q1: '1:32.734' },
      { position: 10, driver_number: 30, name: 'Liam Lawson',       acronym: 'LAW', team: 'Racing Bulls',    team_colour: '#6692FF', time: '1:31.415', gap: '1.197', dnf: false, q3: '1:31.415', q2: '1:32.312', q1: '1:32.867' },
      { position: 11, driver_number: 43, name: 'Franco Colapinto',  acronym: 'COL', team: 'Alpine',          team_colour: '#FF69B4', time: '1:32.401', gap: '2.183', dnf: false, q3: null,        q2: '1:32.401', q1: '1:32.934' },
      { position: 12, driver_number: 6,  name: 'Isack Hadjar',      acronym: 'HAD', team: 'Red Bull Racing', team_colour: '#3671C6', time: '1:32.534', gap: '2.316', dnf: false, q3: null,        q2: '1:32.534', q1: '1:33.067' },
      { position: 13, driver_number: 5,  name: 'Gabriel Bortoleto', acronym: 'BOR', team: 'Audi',            team_colour: '#C0C0C0', time: '1:32.671', gap: '2.453', dnf: false, q3: null,        q2: '1:32.671', q1: '1:33.212' },
      { position: 14, driver_number: 55, name: 'Carlos Sainz',      acronym: 'SAI', team: 'Williams',        team_colour: '#64C4FF', time: '1:32.810', gap: '2.592', dnf: false, q3: null,        q2: '1:32.810', q1: '1:33.356' },
      { position: 15, driver_number: 23, name: 'Alex Albon',        acronym: 'ALB', team: 'Williams',        team_colour: '#64C4FF', time: '1:32.955', gap: '2.737', dnf: false, q3: null,        q2: '1:32.955', q1: '1:33.489' },
      { position: 16, driver_number: 14, name: 'Fernando Alonso',   acronym: 'ALO', team: 'Aston Martin',    team_colour: '#358C75', time: '1:33.102', gap: '2.884', dnf: false, q3: null,        q2: null,        q1: '1:33.102' },
      { position: 17, driver_number: 27, name: 'Nico Hülkenberg',   acronym: 'HUL', team: 'Audi',            team_colour: '#C0C0C0', time: '1:33.241', gap: '3.023', dnf: false, q3: null,        q2: null,        q1: '1:33.241' },
      { position: 18, driver_number: 7,  name: 'Arvid Lindblad',    acronym: 'LIN', team: 'Racing Bulls',    team_colour: '#6692FF', time: '1:33.380', gap: '3.162', dnf: false, q3: null,        q2: null,        q1: '1:33.380' },
      { position: 19, driver_number: 31, name: 'Esteban Ocon',      acronym: 'OCO', team: 'Haas',            team_colour: '#B6BABD', time: '1:33.512', gap: '3.294', dnf: false, q3: null,        q2: null,        q1: '1:33.512' },
      { position: 20, driver_number: 18, name: 'Lance Stroll',      acronym: 'STR', team: 'Aston Martin',    team_colour: '#358C75', time: '1:33.651', gap: '3.433', dnf: false, q3: null,        q2: null,        q1: '1:33.651' },
      { position: 21, driver_number: 77, name: 'Valtteri Bottas',   acronym: 'BOT', team: 'Cadillac',        team_colour: '#CC0000', time: '1:33.798', gap: '3.580', dnf: false, q3: null,        q2: null,        q1: '1:33.798' },
      { position: 22, driver_number: 11, name: 'Sergio Pérez',      acronym: 'PER', team: 'Cadillac',        team_colour: '#CC0000', time: '1:33.941', gap: '3.723', dnf: false, q3: null,        q2: null,        q1: '1:33.941' },
    ],
    fp1: [],
    sprint: [
      { position: 1,  driver_number: 63, name: 'George Russell',    acronym: 'RUS', team: 'Mercedes',        team_colour: '#27F4D2', time: '28:14.521', gap: null,      dnf: false },
      { position: 2,  driver_number: 12, name: 'Kimi Antonelli',    acronym: 'ANT', team: 'Mercedes',        team_colour: '#27F4D2', time: null,        gap: '+2.1s',   dnf: false },
      { position: 3,  driver_number: 44, name: 'Lewis Hamilton',    acronym: 'HAM', team: 'Ferrari',         team_colour: '#E8002D', time: null,        gap: '+8.3s',   dnf: false },
      { position: 4,  driver_number: 16, name: 'Charles Leclerc',   acronym: 'LEC', team: 'Ferrari',         team_colour: '#E8002D', time: null,        gap: '+11.7s',  dnf: false },
      { position: 5,  driver_number: 4,  name: 'Lando Norris',      acronym: 'NOR', team: 'McLaren',         team_colour: '#FF8000', time: null,        gap: '+14.2s',  dnf: false },
      { position: 6,  driver_number: 87, name: 'Oliver Bearman',    acronym: 'BEA', team: 'Haas',            team_colour: '#B6BABD', time: null,        gap: '+18.9s',  dnf: false },
      { position: 7,  driver_number: 1,  name: 'Max Verstappen',    acronym: 'VER', team: 'Red Bull Racing', team_colour: '#3671C6', time: null,        gap: '+22.1s',  dnf: false },
      { position: 8,  driver_number: 30, name: 'Liam Lawson',       acronym: 'LAW', team: 'Racing Bulls',    team_colour: '#6692FF', time: null,        gap: '+25.4s',  dnf: false },
      { position: 9,  driver_number: 81, name: 'Oscar Piastri',     acronym: 'PIA', team: 'McLaren',         team_colour: '#FF8000', time: null,        gap: '+29.1s',  dnf: false },
      { position: 10, driver_number: 10, name: 'Pierre Gasly',      acronym: 'GAS', team: 'Alpine',          team_colour: '#FF69B4', time: null,        gap: '+33.8s',  dnf: false },
      { position: 11, driver_number: 43, name: 'Franco Colapinto',  acronym: 'COL', team: 'Alpine',          team_colour: '#FF69B4', time: null,        gap: '+37.2s',  dnf: false },
      { position: 12, driver_number: 6,  name: 'Isack Hadjar',      acronym: 'HAD', team: 'Red Bull Racing', team_colour: '#3671C6', time: null,        gap: '+40.5s',  dnf: false },
      { position: 13, driver_number: 5,  name: 'Gabriel Bortoleto', acronym: 'BOR', team: 'Audi',            team_colour: '#C0C0C0', time: null,        gap: '+44.1s',  dnf: false },
      { position: 14, driver_number: 55, name: 'Carlos Sainz',      acronym: 'SAI', team: 'Williams',        team_colour: '#64C4FF', time: null,        gap: '+47.8s',  dnf: false },
      { position: 15, driver_number: 23, name: 'Alex Albon',        acronym: 'ALB', team: 'Williams',        team_colour: '#64C4FF', time: null,        gap: '+51.2s',  dnf: false },
      { position: 16, driver_number: 14, name: 'Fernando Alonso',   acronym: 'ALO', team: 'Aston Martin',    team_colour: '#358C75', time: null,        gap: '+54.9s',  dnf: false },
      { position: 17, driver_number: 27, name: 'Nico Hülkenberg',   acronym: 'HUL', team: 'Audi',            team_colour: '#C0C0C0', time: null,        gap: '+58.3s',  dnf: false },
      { position: 18, driver_number: 7,  name: 'Arvid Lindblad',    acronym: 'LIN', team: 'Racing Bulls',    team_colour: '#6692FF', time: null,        gap: '+1:01.7', dnf: false },
      { position: 19, driver_number: 31, name: 'Esteban Ocon',      acronym: 'OCO', team: 'Haas',            team_colour: '#B6BABD', time: null,        gap: '+1:05.4', dnf: false },
      { position: 20, driver_number: 18, name: 'Lance Stroll',      acronym: 'STR', team: 'Aston Martin',    team_colour: '#358C75', time: null,        gap: '+1:09.1', dnf: false },
      { position: 21, driver_number: 77, name: 'Valtteri Bottas',   acronym: 'BOT', team: 'Cadillac',        team_colour: '#CC0000', time: null,        gap: '+1:12.8', dnf: false },
      { position: 22, driver_number: 11, name: 'Sergio Pérez',      acronym: 'PER', team: 'Cadillac',        team_colour: '#CC0000', time: null,        gap: '+1:16.2', dnf: false },
    ],
    'sprint-qualifying': [
      { position: 1,  driver_number: 63, name: 'George Russell',    acronym: 'RUS', team: 'Mercedes',        team_colour: '#27F4D2', time: '1:31.204', gap: null,     dnf: false },
      { position: 2,  driver_number: 12, name: 'Kimi Antonelli',    acronym: 'ANT', team: 'Mercedes',        team_colour: '#27F4D2', time: '1:31.415', gap: '+0.211', dnf: false },
      { position: 3,  driver_number: 44, name: 'Lewis Hamilton',    acronym: 'HAM', team: 'Ferrari',         team_colour: '#E8002D', time: '1:31.688', gap: '+0.484', dnf: false },
      { position: 4,  driver_number: 16, name: 'Charles Leclerc',   acronym: 'LEC', team: 'Ferrari',         team_colour: '#E8002D', time: '1:31.802', gap: '+0.598', dnf: false },
      { position: 5,  driver_number: 4,  name: 'Lando Norris',      acronym: 'NOR', team: 'McLaren',         team_colour: '#FF8000', time: '1:32.011', gap: '+0.807', dnf: false },
      { position: 6,  driver_number: 87, name: 'Oliver Bearman',    acronym: 'BEA', team: 'Haas',            team_colour: '#B6BABD', time: '1:32.245', gap: '+1.041', dnf: false },
      { position: 7,  driver_number: 1,  name: 'Max Verstappen',    acronym: 'VER', team: 'Red Bull Racing', team_colour: '#3671C6', time: '1:32.389', gap: '+1.185', dnf: false },
      { position: 8,  driver_number: 30, name: 'Liam Lawson',       acronym: 'LAW', team: 'Racing Bulls',    team_colour: '#6692FF', time: '1:32.504', gap: '+1.300', dnf: false },
      { position: 9,  driver_number: 81, name: 'Oscar Piastri',     acronym: 'PIA', team: 'McLaren',         team_colour: '#FF8000', time: '1:32.641', gap: '+1.437', dnf: false },
      { position: 10, driver_number: 10, name: 'Pierre Gasly',      acronym: 'GAS', team: 'Alpine',          team_colour: '#FF69B4', time: '1:32.788', gap: '+1.584', dnf: false },
      { position: 11, driver_number: 43, name: 'Franco Colapinto',  acronym: 'COL', team: 'Alpine',          team_colour: '#FF69B4', time: '1:32.921', gap: '+1.717', dnf: false },
      { position: 12, driver_number: 6,  name: 'Isack Hadjar',      acronym: 'HAD', team: 'Red Bull Racing', team_colour: '#3671C6', time: '1:33.054', gap: '+1.850', dnf: false },
      { position: 13, driver_number: 5,  name: 'Gabriel Bortoleto', acronym: 'BOR', team: 'Audi',            team_colour: '#C0C0C0', time: '1:33.198', gap: '+1.994', dnf: false },
      { position: 14, driver_number: 55, name: 'Carlos Sainz',      acronym: 'SAI', team: 'Williams',        team_colour: '#64C4FF', time: '1:33.341', gap: '+2.137', dnf: false },
      { position: 15, driver_number: 23, name: 'Alex Albon',        acronym: 'ALB', team: 'Williams',        team_colour: '#64C4FF', time: '1:33.484', gap: '+2.280', dnf: false },
      { position: 16, driver_number: 14, name: 'Fernando Alonso',   acronym: 'ALO', team: 'Aston Martin',    team_colour: '#358C75', time: '1:33.621', gap: '+2.417', dnf: false },
      { position: 17, driver_number: 27, name: 'Nico Hülkenberg',   acronym: 'HUL', team: 'Audi',            team_colour: '#C0C0C0', time: '1:33.758', gap: '+2.554', dnf: false },
      { position: 18, driver_number: 7,  name: 'Arvid Lindblad',    acronym: 'LIN', team: 'Racing Bulls',    team_colour: '#6692FF', time: '1:33.901', gap: '+2.697', dnf: false },
      { position: 19, driver_number: 31, name: 'Esteban Ocon',      acronym: 'OCO', team: 'Haas',            team_colour: '#B6BABD', time: '1:34.044', gap: '+2.840', dnf: false },
      { position: 20, driver_number: 18, name: 'Lance Stroll',      acronym: 'STR', team: 'Aston Martin',    team_colour: '#358C75', time: '1:34.187', gap: '+2.983', dnf: false },
      { position: 21, driver_number: 77, name: 'Valtteri Bottas',   acronym: 'BOT', team: 'Cadillac',        team_colour: '#CC0000', time: '1:34.330', gap: '+3.126', dnf: false },
      { position: 22, driver_number: 11, name: 'Sergio Pérez',      acronym: 'PER', team: 'Cadillac',        team_colour: '#CC0000', time: '1:34.471', gap: '+3.267', dnf: false },
    ],
  },
}
