export interface Session {
  name: string
  short?: string
  date: string
  dateISO?: string
  timeUTC: string
  timeLocal: string
  completed: boolean
}

export interface Race {
  round: number
  name: string
  shortName: string
  circuit: string
  country: string
  flag: string
  isSprint: boolean
  sessions: Session[]
}

export const CURRENT_RACE: Race = {
  round: 3,
  name: 'Japanese Grand Prix',
  shortName: 'Japan',
  circuit: 'Suzuka Circuit',
  country: 'Japan',
  flag: '🇯🇵',
  isSprint: false,
  sessions: [
    { name: 'Practice 1',  short: 'FP1',  date: 'Fri 27 Mar', dateISO: '2026-03-27T02:30:00Z', timeUTC: '02:30 UTC', timeLocal: '11:30 JST', completed: false },
    { name: 'Practice 2',  short: 'FP2',  date: 'Fri 27 Mar', dateISO: '2026-03-27T06:00:00Z', timeUTC: '06:00 UTC', timeLocal: '15:00 JST', completed: false },
    { name: 'Practice 3',  short: 'FP3',  date: 'Sat 28 Mar', dateISO: '2026-03-28T02:30:00Z', timeUTC: '02:30 UTC', timeLocal: '11:30 JST', completed: false },
    { name: 'Qualifying',  short: 'QUAL', date: 'Sat 28 Mar', dateISO: '2026-03-28T06:00:00Z', timeUTC: '06:00 UTC', timeLocal: '15:00 JST', completed: false },
    { name: 'Race',        short: 'RACE', date: 'Sun 29 Mar', dateISO: '2026-03-29T05:00:00Z', timeUTC: '05:00 UTC', timeLocal: '14:00 JST', completed: false },
  ],
}

export const SEASON_CALENDAR: {
  round: number
  name: string
  flag: string
  country: string
  circuit: string
  date: string
  dateRange: string
  sprint: boolean
  completed: boolean
  calledOff: boolean
  meeting_key?: number
  lat?: number
  lon?: number
  weekendStartISO?: string
}[] = [
  {
    round: 1,
    name: 'Australia',
    flag: '🇦🇺',
    country: 'Australia',
    circuit: 'Albert Park Circuit',
    date: '8 Mar',
    dateRange: '6–8 Mar',
    sprint: false,
    completed: true,
    calledOff: false,
    meeting_key: 1279,
    lat: -37.8497,
    lon: 144.9680,
    weekendStartISO: '2026-03-06',
  },
  {
    round: 2,
    name: 'China',
    flag: '🇨🇳',
    country: 'China',
    circuit: 'Shanghai International Circuit',
    date: '15 Mar',
    dateRange: '13–15 Mar',
    sprint: true,
    completed: true,
    calledOff: false,
    meeting_key: 1280,
    lat: 31.3389,
    lon: 121.2200,
    weekendStartISO: '2026-03-13',
  },
  {
    round: 3,
    name: 'Japan',
    flag: '🇯🇵',
    country: 'Japan',
    circuit: 'Suzuka Circuit',
    date: '29 Mar',
    dateRange: '27–29 Mar',
    sprint: false,
    completed: false,
    calledOff: false,
    lat: 34.8431,
    lon: 136.5417,
    weekendStartISO: '2026-03-27',
  },
  {
    round: 4,
    name: 'Miami',
    flag: '🇺🇸',
    country: 'United States',
    circuit: 'Miami International Autodrome',
    date: '3 May',
    dateRange: '1–3 May',
    sprint: true,
    completed: false,
    calledOff: false,
    lat: 25.9581,
    lon: -80.2389,
    weekendStartISO: '2026-05-01',
  },
  {
    round: 5,
    name: 'Canada',
    flag: '🇨🇦',
    country: 'Canada',
    circuit: 'Circuit Gilles Villeneuve',
    date: '24 May',
    dateRange: '22–24 May',
    sprint: true,
    completed: false,
    calledOff: false,
    lat: 45.5048,
    lon: -73.5228,
    weekendStartISO: '2026-05-22',
  },
  {
    round: 6,
    name: 'Monaco',
    flag: '🇲🇨',
    country: 'Monaco',
    circuit: 'Circuit de Monaco',
    date: '7 Jun',
    dateRange: '5–7 Jun',
    sprint: false,
    completed: false,
    calledOff: false,
    lat: 43.7347,
    lon: 7.4206,
    weekendStartISO: '2026-06-05',
  },
  {
    round: 7,
    name: 'Barcelona-Catalunya',
    flag: '🇪🇸',
    country: 'Spain',
    circuit: 'Circuit de Barcelona-Catalunya',
    date: '14 Jun',
    dateRange: '12–14 Jun',
    sprint: false,
    completed: false,
    calledOff: false,
    lat: 41.5700,
    lon: 2.2611,
    weekendStartISO: '2026-06-12',
  },
  {
    round: 8,
    name: 'Austria',
    flag: '🇦🇹',
    country: 'Austria',
    circuit: 'Red Bull Ring',
    date: '28 Jun',
    dateRange: '26–28 Jun',
    sprint: false,
    completed: false,
    calledOff: false,
    lat: 47.2197,
    lon: 14.7647,
    weekendStartISO: '2026-06-26',
  },
  {
    round: 9,
    name: 'Britain',
    flag: '🇬🇧',
    country: 'Great Britain',
    circuit: 'Silverstone Circuit',
    date: '5 Jul',
    dateRange: '3–5 Jul',
    sprint: true,
    completed: false,
    calledOff: false,
    lat: 52.0786,
    lon: -1.0169,
    weekendStartISO: '2026-07-03',
  },
  {
    round: 10,
    name: 'Belgium',
    flag: '🇧🇪',
    country: 'Belgium',
    circuit: 'Circuit de Spa-Francorchamps',
    date: '19 Jul',
    dateRange: '17–19 Jul',
    sprint: false,
    completed: false,
    calledOff: false,
    lat: 50.4372,
    lon: 5.9714,
    weekendStartISO: '2026-07-17',
  },
  {
    round: 11,
    name: 'Hungary',
    flag: '🇭🇺',
    country: 'Hungary',
    circuit: 'Hungaroring',
    date: '26 Jul',
    dateRange: '24–26 Jul',
    sprint: false,
    completed: false,
    calledOff: false,
    lat: 47.5830,
    lon: 19.2486,
    weekendStartISO: '2026-07-24',
  },
  {
    round: 12,
    name: 'Netherlands',
    flag: '🇳🇱',
    country: 'Netherlands',
    circuit: 'Circuit Zandvoort',
    date: '23 Aug',
    dateRange: '21–23 Aug',
    sprint: true,
    completed: false,
    calledOff: false,
    lat: 52.3888,
    lon: 4.5409,
    weekendStartISO: '2026-08-21',
  },
  {
    round: 13,
    name: 'Italy',
    flag: '🇮🇹',
    country: 'Italy',
    circuit: 'Autodromo Nazionale Monza',
    date: '6 Sep',
    dateRange: '4–6 Sep',
    sprint: false,
    completed: false,
    calledOff: false,
    lat: 45.6156,
    lon: 9.2811,
    weekendStartISO: '2026-09-04',
  },
  {
    round: 14,
    name: 'Madrid',
    flag: '🇪🇸',
    country: 'Spain',
    circuit: 'Madring Street Circuit',
    date: '13 Sep',
    dateRange: '11–13 Sep',
    sprint: false,
    completed: false,
    calledOff: false,
    lat: 40.4168,
    lon: -3.7038,
    weekendStartISO: '2026-09-11',
  },
  {
    round: 15,
    name: 'Azerbaijan',
    flag: '🇦🇿',
    country: 'Azerbaijan',
    circuit: 'Baku City Circuit',
    date: '26 Sep',
    dateRange: '24–26 Sep',
    sprint: false,
    completed: false,
    calledOff: false,
    lat: 40.3725,
    lon: 49.8533,
    weekendStartISO: '2026-09-24',
  },
  {
    round: 16,
    name: 'Singapore',
    flag: '🇸🇬',
    country: 'Singapore',
    circuit: 'Marina Bay Street Circuit',
    date: '11 Oct',
    dateRange: '9–11 Oct',
    sprint: true,
    completed: false,
    calledOff: false,
    lat: 1.2914,
    lon: 103.8639,
    weekendStartISO: '2026-10-09',
  },
  {
    round: 17,
    name: 'United States',
    flag: '🇺🇸',
    country: 'United States',
    circuit: 'Circuit of the Americas',
    date: '25 Oct',
    dateRange: '23–25 Oct',
    sprint: false,
    completed: false,
    calledOff: false,
    lat: 30.1328,
    lon: -97.6411,
    weekendStartISO: '2026-10-23',
  },
  {
    round: 18,
    name: 'Mexico',
    flag: '🇲🇽',
    country: 'Mexico',
    circuit: 'Autodromo Hermanos Rodriguez',
    date: '1 Nov',
    dateRange: '30 Oct–1 Nov',
    sprint: false,
    completed: false,
    calledOff: false,
    lat: 19.4042,
    lon: -99.0907,
    weekendStartISO: '2026-10-30',
  },
  {
    round: 19,
    name: 'Brazil',
    flag: '🇧🇷',
    country: 'Brazil',
    circuit: 'Autodromo Jose Carlos Pace',
    date: '8 Nov',
    dateRange: '6–8 Nov',
    sprint: false,
    completed: false,
    calledOff: false,
    lat: -23.7036,
    lon: -46.6997,
    weekendStartISO: '2026-11-06',
  },
  {
    round: 20,
    name: 'Las Vegas',
    flag: '🇺🇸',
    country: 'United States',
    circuit: 'Las Vegas Strip Circuit',
    date: '21 Nov',
    dateRange: '19–21 Nov',
    sprint: false,
    completed: false,
    calledOff: false,
    lat: 36.1699,
    lon: -115.1398,
    weekendStartISO: '2026-11-19',
  },
  {
    round: 21,
    name: 'Qatar',
    flag: '🇶🇦',
    country: 'Qatar',
    circuit: 'Lusail International Circuit',
    date: '29 Nov',
    dateRange: '27–29 Nov',
    sprint: false,
    completed: false,
    calledOff: false,
    lat: 25.4900,
    lon: 51.4500,
    weekendStartISO: '2026-11-27',
  },
  {
    round: 22,
    name: 'Abu Dhabi',
    flag: '🇦🇪',
    country: 'United Arab Emirates',
    circuit: 'Yas Marina Circuit',
    date: '6 Dec',
    dateRange: '4–6 Dec',
    sprint: false,
    completed: false,
    calledOff: false,
    lat: 24.4672,
    lon: 54.6031,
    weekendStartISO: '2026-12-04',
  },
]
