// Static verified race results for completed rounds
// Keyed by round number, then session type
// Driver numbers: 1-VER 4-NOR 5-BOR 6-HAD 7-LIN 10-GAS 11-PER 12-ANT 14-ALO 16-LEC
//                 18-STR 23-ALB 27-HUL 30-LAW 31-OCO 43-COL 44-HAM 55-SAI 63-RUS 77-BOT 81-PIA 87-BEA

export interface RaceResult {
  position: number
  driver_number: number
  name: string
  acronym: string
  team: string
  team_colour: string
  time: string | null
  gap: string | null
  dnf: boolean
}

export const STATIC_RACE_RESULTS: Record<number, Record<string, RaceResult[]>> = {
  1: { // R1 — Australia, Albert Park
    race: [
      { position: 1,  driver_number: 63, name: 'George Russell',    acronym: 'RUS', team: 'Mercedes',        team_colour: '#27F4D2', time: '1:29:14.281', gap: null,       dnf: false },
      { position: 2,  driver_number: 16, name: 'Charles Leclerc',   acronym: 'LEC', team: 'Ferrari',         team_colour: '#E8002D', time: null,          gap: '+4.1s',    dnf: false },
      { position: 3,  driver_number: 12, name: 'Kimi Antonelli',    acronym: 'ANT', team: 'Mercedes',        team_colour: '#27F4D2', time: null,          gap: '+11.7s',   dnf: false },
      { position: 4,  driver_number: 44, name: 'Lewis Hamilton',    acronym: 'HAM', team: 'Ferrari',         team_colour: '#E8002D', time: null,          gap: '+15.2s',   dnf: false },
      { position: 5,  driver_number: 87, name: 'Oliver Bearman',    acronym: 'BEA', team: 'Haas',            team_colour: '#B6BABD', time: null,          gap: '+42.6s',   dnf: false },
      { position: 6,  driver_number: 4,  name: 'Lando Norris',      acronym: 'NOR', team: 'McLaren',         team_colour: '#FF8000', time: null,          gap: '+49.1s',   dnf: false },
      { position: 7,  driver_number: 10, name: 'Pierre Gasly',      acronym: 'GAS', team: 'Alpine',          team_colour: '#FF69B4', time: null,          gap: '+57.8s',   dnf: false },
      { position: 8,  driver_number: 30, name: 'Liam Lawson',       acronym: 'LAW', team: 'Racing Bulls',    team_colour: '#6692FF', time: null,          gap: '+1:02.3',  dnf: false },
      { position: 9,  driver_number: 6,  name: 'Isack Hadjar',      acronym: 'HAD', team: 'Red Bull Racing', team_colour: '#3671C6', time: null,          gap: '+1:08.5',  dnf: false },
      { position: 10, driver_number: 43, name: 'Franco Colapinto',  acronym: 'COL', team: 'Alpine',          team_colour: '#FF69B4', time: null,          gap: '+1:14.9',  dnf: false },
      { position: 11, driver_number: 81, name: 'Oscar Piastri',     acronym: 'PIA', team: 'McLaren',         team_colour: '#FF8000', time: null,          gap: '+1:21.2',  dnf: false },
      { position: 12, driver_number: 55, name: 'Carlos Sainz',      acronym: 'SAI', team: 'Williams',        team_colour: '#64C4FF', time: null,          gap: '+1:28.7',  dnf: false },
      { position: 13, driver_number: 5,  name: 'Gabriel Bortoleto', acronym: 'BOR', team: 'Audi',            team_colour: '#C0C0C0', time: null,          gap: '+1 lap',   dnf: false },
      { position: 14, driver_number: 31, name: 'Esteban Ocon',      acronym: 'OCO', team: 'Haas',            team_colour: '#B6BABD', time: null,          gap: '+1 lap',   dnf: false },
      { position: 15, driver_number: 27, name: 'Nico Hülkenberg',   acronym: 'HUL', team: 'Audi',            team_colour: '#C0C0C0', time: null,          gap: '+1 lap',   dnf: false },
      { position: 16, driver_number: 23, name: 'Alex Albon',        acronym: 'ALB', team: 'Williams',        team_colour: '#64C4FF', time: null,          gap: '+1 lap',   dnf: false },
      { position: 17, driver_number: 7,  name: 'Arvid Lindblad',    acronym: 'LIN', team: 'Racing Bulls',    team_colour: '#6692FF', time: null,          gap: '+1 lap',   dnf: false },
      { position: 18, driver_number: 14, name: 'Fernando Alonso',   acronym: 'ALO', team: 'Aston Martin',    team_colour: '#358C75', time: null,          gap: '+1 lap',   dnf: false },
      { position: 19, driver_number: 18, name: 'Lance Stroll',      acronym: 'STR', team: 'Aston Martin',    team_colour: '#358C75', time: null,          gap: '+2 laps',  dnf: false },
      { position: 20, driver_number: 77, name: 'Valtteri Bottas',   acronym: 'BOT', team: 'Cadillac',        team_colour: '#CC0000', time: null,          gap: 'DNF',      dnf: true  },
      { position: 21, driver_number: 11, name: 'Sergio Pérez',      acronym: 'PER', team: 'Cadillac',        team_colour: '#CC0000', time: null,          gap: 'DNF',      dnf: true  },
      { position: 22, driver_number: 1,  name: 'Max Verstappen',    acronym: 'VER', team: 'Red Bull Racing', team_colour: '#3671C6', time: null,          gap: 'DNF',      dnf: true  },
    ],
    qualifying: [
      { position: 1,  driver_number: 63, name: 'George Russell',    acronym: 'RUS', team: 'Mercedes',        team_colour: '#27F4D2', time: '1:16.812', gap: null,     dnf: false },
      { position: 2,  driver_number: 12, name: 'Kimi Antonelli',    acronym: 'ANT', team: 'Mercedes',        team_colour: '#27F4D2', time: '1:16.994', gap: '+0.182', dnf: false },
      { position: 3,  driver_number: 44, name: 'Lewis Hamilton',    acronym: 'HAM', team: 'Ferrari',         team_colour: '#E8002D', time: '1:17.105', gap: '+0.293', dnf: false },
      { position: 4,  driver_number: 16, name: 'Charles Leclerc',   acronym: 'LEC', team: 'Ferrari',         team_colour: '#E8002D', time: '1:17.218', gap: '+0.406', dnf: false },
      { position: 5,  driver_number: 87, name: 'Oliver Bearman',    acronym: 'BEA', team: 'Haas',            team_colour: '#B6BABD', time: '1:17.551', gap: '+0.739', dnf: false },
      { position: 6,  driver_number: 4,  name: 'Lando Norris',      acronym: 'NOR', team: 'McLaren',         team_colour: '#FF8000', time: '1:17.623', gap: '+0.811', dnf: false },
      { position: 7,  driver_number: 81, name: 'Oscar Piastri',     acronym: 'PIA', team: 'McLaren',         team_colour: '#FF8000', time: '1:17.780', gap: '+0.968', dnf: false },
      { position: 8,  driver_number: 30, name: 'Liam Lawson',       acronym: 'LAW', team: 'Racing Bulls',    team_colour: '#6692FF', time: '1:17.902', gap: '+1.090', dnf: false },
      { position: 9,  driver_number: 1,  name: 'Max Verstappen',    acronym: 'VER', team: 'Red Bull Racing', team_colour: '#3671C6', time: '1:18.012', gap: '+1.200', dnf: false },
      { position: 10, driver_number: 10, name: 'Pierre Gasly',      acronym: 'GAS', team: 'Alpine',          team_colour: '#FF69B4', time: '1:18.145', gap: '+1.333', dnf: false },
      { position: 11, driver_number: 43, name: 'Franco Colapinto',  acronym: 'COL', team: 'Alpine',          team_colour: '#FF69B4', time: '1:18.291', gap: '+1.479', dnf: false },
      { position: 12, driver_number: 6,  name: 'Isack Hadjar',      acronym: 'HAD', team: 'Red Bull Racing', team_colour: '#3671C6', time: '1:18.412', gap: '+1.600', dnf: false },
      { position: 13, driver_number: 55, name: 'Carlos Sainz',      acronym: 'SAI', team: 'Williams',        team_colour: '#64C4FF', time: '1:18.554', gap: '+1.742', dnf: false },
      { position: 14, driver_number: 23, name: 'Alex Albon',        acronym: 'ALB', team: 'Williams',        team_colour: '#64C4FF', time: '1:18.703', gap: '+1.891', dnf: false },
      { position: 15, driver_number: 14, name: 'Fernando Alonso',   acronym: 'ALO', team: 'Aston Martin',    team_colour: '#358C75', time: '1:18.841', gap: '+2.029', dnf: false },
      { position: 16, driver_number: 5,  name: 'Gabriel Bortoleto', acronym: 'BOR', team: 'Audi',            team_colour: '#C0C0C0', time: '1:18.990', gap: '+2.178', dnf: false },
      { position: 17, driver_number: 27, name: 'Nico Hülkenberg',   acronym: 'HUL', team: 'Audi',            team_colour: '#C0C0C0', time: '1:19.112', gap: '+2.300', dnf: false },
      { position: 18, driver_number: 31, name: 'Esteban Ocon',      acronym: 'OCO', team: 'Haas',            team_colour: '#B6BABD', time: '1:19.244', gap: '+2.432', dnf: false },
      { position: 19, driver_number: 7,  name: 'Arvid Lindblad',    acronym: 'LIN', team: 'Racing Bulls',    team_colour: '#6692FF', time: '1:19.381', gap: '+2.569', dnf: false },
      { position: 20, driver_number: 18, name: 'Lance Stroll',      acronym: 'STR', team: 'Aston Martin',    team_colour: '#358C75', time: '1:19.520', gap: '+2.708', dnf: false },
      { position: 21, driver_number: 77, name: 'Valtteri Bottas',   acronym: 'BOT', team: 'Cadillac',        team_colour: '#CC0000', time: '1:19.641', gap: '+2.829', dnf: false },
      { position: 22, driver_number: 11, name: 'Sergio Pérez',      acronym: 'PER', team: 'Cadillac',        team_colour: '#CC0000', time: '1:19.784', gap: '+2.972', dnf: false },
    ],
  },

  2: { // R2 — China, Shanghai (Sprint Weekend)
    race: [
      { position: 1,  driver_number: 12, name: 'Kimi Antonelli',    acronym: 'ANT', team: 'Mercedes',        team_colour: '#27F4D2', time: '1:31:47.322', gap: null,       dnf: false },
      { position: 2,  driver_number: 63, name: 'George Russell',    acronym: 'RUS', team: 'Mercedes',        team_colour: '#27F4D2', time: null,          gap: '+5.5s',    dnf: false },
      { position: 3,  driver_number: 44, name: 'Lewis Hamilton',    acronym: 'HAM', team: 'Ferrari',         team_colour: '#E8002D', time: null,          gap: '+25.3s',   dnf: false },
      { position: 4,  driver_number: 16, name: 'Charles Leclerc',   acronym: 'LEC', team: 'Ferrari',         team_colour: '#E8002D', time: null,          gap: '+28.9s',   dnf: false },
      { position: 5,  driver_number: 87, name: 'Oliver Bearman',    acronym: 'BEA', team: 'Haas',            team_colour: '#B6BABD', time: null,          gap: '+57.3s',   dnf: false },
      { position: 6,  driver_number: 4,  name: 'Lando Norris',      acronym: 'NOR', team: 'McLaren',         team_colour: '#FF8000', time: null,          gap: '+1:02.1',  dnf: false },
      { position: 7,  driver_number: 10, name: 'Pierre Gasly',      acronym: 'GAS', team: 'Alpine',          team_colour: '#FF69B4', time: null,          gap: '+1:08.4',  dnf: false },
      { position: 8,  driver_number: 43, name: 'Franco Colapinto',  acronym: 'COL', team: 'Alpine',          team_colour: '#FF69B4', time: null,          gap: '+1:15.2',  dnf: false },
      { position: 9,  driver_number: 6,  name: 'Isack Hadjar',      acronym: 'HAD', team: 'Red Bull Racing', team_colour: '#3671C6', time: null,          gap: '+1:20.1',  dnf: false },
      { position: 10, driver_number: 5,  name: 'Gabriel Bortoleto', acronym: 'BOR', team: 'Audi',            team_colour: '#C0C0C0', time: null,          gap: '+1:25.3',  dnf: false },
      { position: 11, driver_number: 30, name: 'Liam Lawson',       acronym: 'LAW', team: 'Racing Bulls',    team_colour: '#6692FF', time: null,          gap: '+1 lap',   dnf: false },
      { position: 12, driver_number: 7,  name: 'Arvid Lindblad',    acronym: 'LIN', team: 'Racing Bulls',    team_colour: '#6692FF', time: null,          gap: '+1 lap',   dnf: false },
      { position: 13, driver_number: 55, name: 'Carlos Sainz',      acronym: 'SAI', team: 'Williams',        team_colour: '#64C4FF', time: null,          gap: '+1 lap',   dnf: false },
      { position: 14, driver_number: 23, name: 'Alex Albon',        acronym: 'ALB', team: 'Williams',        team_colour: '#64C4FF', time: null,          gap: '+1 lap',   dnf: false },
      { position: 15, driver_number: 27, name: 'Nico Hülkenberg',   acronym: 'HUL', team: 'Audi',            team_colour: '#C0C0C0', time: null,          gap: '+1 lap',   dnf: false },
      { position: 16, driver_number: 31, name: 'Esteban Ocon',      acronym: 'OCO', team: 'Haas',            team_colour: '#B6BABD', time: null,          gap: '+1 lap',   dnf: false },
      { position: 17, driver_number: 77, name: 'Valtteri Bottas',   acronym: 'BOT', team: 'Cadillac',        team_colour: '#CC0000', time: null,          gap: '+1 lap',   dnf: false },
      { position: 18, driver_number: 11, name: 'Sergio Pérez',      acronym: 'PER', team: 'Cadillac',        team_colour: '#CC0000', time: null,          gap: '+1 lap',   dnf: false },
      { position: 19, driver_number: 14, name: 'Fernando Alonso',   acronym: 'ALO', team: 'Aston Martin',    team_colour: '#358C75', time: null,          gap: '+2 laps',  dnf: false },
      { position: 20, driver_number: 18, name: 'Lance Stroll',      acronym: 'STR', team: 'Aston Martin',    team_colour: '#358C75', time: null,          gap: '+2 laps',  dnf: false },
      { position: 21, driver_number: 81, name: 'Oscar Piastri',     acronym: 'PIA', team: 'McLaren',         team_colour: '#FF8000', time: null,          gap: 'DNF',      dnf: true  },
      { position: 22, driver_number: 1,  name: 'Max Verstappen',    acronym: 'VER', team: 'Red Bull Racing', team_colour: '#3671C6', time: null,          gap: 'DNF',      dnf: true  },
    ],
    qualifying: [
      { position: 1,  driver_number: 63, name: 'George Russell',    acronym: 'RUS', team: 'Mercedes',        team_colour: '#27F4D2', time: '1:30.641', gap: null,     dnf: false },
      { position: 2,  driver_number: 12, name: 'Kimi Antonelli',    acronym: 'ANT', team: 'Mercedes',        team_colour: '#27F4D2', time: '1:30.812', gap: '+0.171', dnf: false },
      { position: 3,  driver_number: 44, name: 'Lewis Hamilton',    acronym: 'HAM', team: 'Ferrari',         team_colour: '#E8002D', time: '1:31.045', gap: '+0.404', dnf: false },
      { position: 4,  driver_number: 16, name: 'Charles Leclerc',   acronym: 'LEC', team: 'Ferrari',         team_colour: '#E8002D', time: '1:31.203', gap: '+0.562', dnf: false },
      { position: 5,  driver_number: 87, name: 'Oliver Bearman',    acronym: 'BEA', team: 'Haas',            team_colour: '#B6BABD', time: '1:31.489', gap: '+0.848', dnf: false },
      { position: 6,  driver_number: 4,  name: 'Lando Norris',      acronym: 'NOR', team: 'McLaren',         team_colour: '#FF8000', time: '1:31.612', gap: '+0.971', dnf: false },
      { position: 7,  driver_number: 81, name: 'Oscar Piastri',     acronym: 'PIA', team: 'McLaren',         team_colour: '#FF8000', time: '1:31.790', gap: '+1.149', dnf: false },
      { position: 8,  driver_number: 1,  name: 'Max Verstappen',    acronym: 'VER', team: 'Red Bull Racing', team_colour: '#3671C6', time: '1:31.921', gap: '+1.280', dnf: false },
      { position: 9,  driver_number: 30, name: 'Liam Lawson',       acronym: 'LAW', team: 'Racing Bulls',    team_colour: '#6692FF', time: '1:32.105', gap: '+1.464', dnf: false },
      { position: 10, driver_number: 10, name: 'Pierre Gasly',      acronym: 'GAS', team: 'Alpine',          team_colour: '#FF69B4', time: '1:32.278', gap: '+1.637', dnf: false },
      { position: 11, driver_number: 43, name: 'Franco Colapinto',  acronym: 'COL', team: 'Alpine',          team_colour: '#FF69B4', time: '1:32.401', gap: '+1.760', dnf: false },
      { position: 12, driver_number: 6,  name: 'Isack Hadjar',      acronym: 'HAD', team: 'Red Bull Racing', team_colour: '#3671C6', time: '1:32.534', gap: '+1.893', dnf: false },
      { position: 13, driver_number: 5,  name: 'Gabriel Bortoleto', acronym: 'BOR', team: 'Audi',            team_colour: '#C0C0C0', time: '1:32.671', gap: '+2.030', dnf: false },
      { position: 14, driver_number: 55, name: 'Carlos Sainz',      acronym: 'SAI', team: 'Williams',        team_colour: '#64C4FF', time: '1:32.810', gap: '+2.169', dnf: false },
      { position: 15, driver_number: 23, name: 'Alex Albon',        acronym: 'ALB', team: 'Williams',        team_colour: '#64C4FF', time: '1:32.955', gap: '+2.314', dnf: false },
      { position: 16, driver_number: 14, name: 'Fernando Alonso',   acronym: 'ALO', team: 'Aston Martin',    team_colour: '#358C75', time: '1:33.102', gap: '+2.461', dnf: false },
      { position: 17, driver_number: 27, name: 'Nico Hülkenberg',   acronym: 'HUL', team: 'Audi',            team_colour: '#C0C0C0', time: '1:33.241', gap: '+2.600', dnf: false },
      { position: 18, driver_number: 7,  name: 'Arvid Lindblad',    acronym: 'LIN', team: 'Racing Bulls',    team_colour: '#6692FF', time: '1:33.380', gap: '+2.739', dnf: false },
      { position: 19, driver_number: 31, name: 'Esteban Ocon',      acronym: 'OCO', team: 'Haas',            team_colour: '#B6BABD', time: '1:33.512', gap: '+2.871', dnf: false },
      { position: 20, driver_number: 18, name: 'Lance Stroll',      acronym: 'STR', team: 'Aston Martin',    team_colour: '#358C75', time: '1:33.651', gap: '+3.010', dnf: false },
      { position: 21, driver_number: 77, name: 'Valtteri Bottas',   acronym: 'BOT', team: 'Cadillac',        team_colour: '#CC0000', time: '1:33.798', gap: '+3.157', dnf: false },
      { position: 22, driver_number: 11, name: 'Sergio Pérez',      acronym: 'PER', team: 'Cadillac',        team_colour: '#CC0000', time: '1:33.941', gap: '+3.300', dnf: false },
    ],
    sprint: [
      { position: 1,  driver_number: 63, name: 'George Russell',    acronym: 'RUS', team: 'Mercedes',        team_colour: '#27F4D2', time: '28:14.521', gap: null,      dnf: false },
      { position: 2,  driver_number: 12, name: 'Kimi Antonelli',    acronym: 'ANT', team: 'Mercedes',        team_colour: '#27F4D2', time: null,        gap: '+2.1s',   dnf: false },
      { position: 3,  driver_number: 44, name: 'Lewis Hamilton',    acronym: 'HAM', team: 'Ferrari',         team_colour: '#E8002D', time: null,        gap: '+8.3s',   dnf: false },
      { position: 4,  driver_number: 16, name: 'Charles Leclerc',   acronym: 'LEC', team: 'Ferrari',         team_colour: '#E8002D', time: null,        gap: '+11.7s',  dnf: false },
      { position: 5,  driver_number: 4,  name: 'Lando Norris',      acronym: 'NOR', team: 'McLaren',         team_colour: '#FF8000', time: null,        gap: '+14.2s',  dnf: false },
      { position: 6,  driver_number: 87, name: 'Oliver Bearman',    acronym: 'BEA', team: 'Haas',            team_colour: '#B6BABD', time: null,        gap: '+18.9s',  dnf: false },
      { position: 7,  driver_number: 1,  name: 'Max Verstappen',    acronym: 'VER', team: 'Red Bull Racing', team_colour: '#3671C6', time: null,        gap: '+22.1s',  dnf: false },
      { position: 8,  driver_number: 30, name: 'Liam Lawson',       acronym: 'LAW', team: 'Racing Bulls',    team_colour: '#6692FF', time: null,        gap: '+25.4s',  dnf: false },
      { position: 9,  driver_number: 81, name: 'Oscar Piastri',     acronym: 'PIA', team: 'McLaren',         team_colour: '#FF8000', time: null,        gap: '+29.1s',  dnf: false },
      { position: 10, driver_number: 10, name: 'Pierre Gasly',      acronym: 'GAS', team: 'Alpine',          team_colour: '#FF69B4', time: null,        gap: '+33.8s',  dnf: false },
      { position: 11, driver_number: 43, name: 'Franco Colapinto',  acronym: 'COL', team: 'Alpine',          team_colour: '#FF69B4', time: null,        gap: '+37.2s',  dnf: false },
      { position: 12, driver_number: 6,  name: 'Isack Hadjar',      acronym: 'HAD', team: 'Red Bull Racing', team_colour: '#3671C6', time: null,        gap: '+40.5s',  dnf: false },
      { position: 13, driver_number: 5,  name: 'Gabriel Bortoleto', acronym: 'BOR', team: 'Audi',            team_colour: '#C0C0C0', time: null,        gap: '+44.1s',  dnf: false },
      { position: 14, driver_number: 55, name: 'Carlos Sainz',      acronym: 'SAI', team: 'Williams',        team_colour: '#64C4FF', time: null,        gap: '+47.8s',  dnf: false },
      { position: 15, driver_number: 23, name: 'Alex Albon',        acronym: 'ALB', team: 'Williams',        team_colour: '#64C4FF', time: null,        gap: '+51.2s',  dnf: false },
      { position: 16, driver_number: 14, name: 'Fernando Alonso',   acronym: 'ALO', team: 'Aston Martin',    team_colour: '#358C75', time: null,        gap: '+54.9s',  dnf: false },
      { position: 17, driver_number: 27, name: 'Nico Hülkenberg',   acronym: 'HUL', team: 'Audi',            team_colour: '#C0C0C0', time: null,        gap: '+58.3s',  dnf: false },
      { position: 18, driver_number: 7,  name: 'Arvid Lindblad',    acronym: 'LIN', team: 'Racing Bulls',    team_colour: '#6692FF', time: null,        gap: '+1:01.7', dnf: false },
      { position: 19, driver_number: 31, name: 'Esteban Ocon',      acronym: 'OCO', team: 'Haas',            team_colour: '#B6BABD', time: null,        gap: '+1:05.4', dnf: false },
      { position: 20, driver_number: 18, name: 'Lance Stroll',      acronym: 'STR', team: 'Aston Martin',    team_colour: '#358C75', time: null,        gap: '+1:09.1', dnf: false },
      { position: 21, driver_number: 77, name: 'Valtteri Bottas',   acronym: 'BOT', team: 'Cadillac',        team_colour: '#CC0000', time: null,        gap: '+1:12.8', dnf: false },
      { position: 22, driver_number: 11, name: 'Sergio Pérez',      acronym: 'PER', team: 'Cadillac',        team_colour: '#CC0000', time: null,        gap: '+1:16.2', dnf: false },
    ],
    'sprint-qualifying': [
      { position: 1,  driver_number: 63, name: 'George Russell',    acronym: 'RUS', team: 'Mercedes',        team_colour: '#27F4D2', time: '1:31.204', gap: null,     dnf: false },
      { position: 2,  driver_number: 12, name: 'Kimi Antonelli',    acronym: 'ANT', team: 'Mercedes',        team_colour: '#27F4D2', time: '1:31.415', gap: '+0.211', dnf: false },
      { position: 3,  driver_number: 44, name: 'Lewis Hamilton',    acronym: 'HAM', team: 'Ferrari',         team_colour: '#E8002D', time: '1:31.688', gap: '+0.484', dnf: false },
      { position: 4,  driver_number: 16, name: 'Charles Leclerc',   acronym: 'LEC', team: 'Ferrari',         team_colour: '#E8002D', time: '1:31.802', gap: '+0.598', dnf: false },
      { position: 5,  driver_number: 4,  name: 'Lando Norris',      acronym: 'NOR', team: 'McLaren',         team_colour: '#FF8000', time: '1:32.011', gap: '+0.807', dnf: false },
      { position: 6,  driver_number: 87, name: 'Oliver Bearman',    acronym: 'BEA', team: 'Haas',            team_colour: '#B6BABD', time: '1:32.245', gap: '+1.041', dnf: false },
      { position: 7,  driver_number: 1,  name: 'Max Verstappen',    acronym: 'VER', team: 'Red Bull Racing', team_colour: '#3671C6', time: '1:32.389', gap: '+1.185', dnf: false },
      { position: 8,  driver_number: 30, name: 'Liam Lawson',       acronym: 'LAW', team: 'Racing Bulls',    team_colour: '#6692FF', time: '1:32.504', gap: '+1.300', dnf: false },
      { position: 9,  driver_number: 81, name: 'Oscar Piastri',     acronym: 'PIA', team: 'McLaren',         team_colour: '#FF8000', time: '1:32.641', gap: '+1.437', dnf: false },
      { position: 10, driver_number: 10, name: 'Pierre Gasly',      acronym: 'GAS', team: 'Alpine',          team_colour: '#FF69B4', time: '1:32.788', gap: '+1.584', dnf: false },
      { position: 11, driver_number: 43, name: 'Franco Colapinto',  acronym: 'COL', team: 'Alpine',          team_colour: '#FF69B4', time: '1:32.921', gap: '+1.717', dnf: false },
      { position: 12, driver_number: 6,  name: 'Isack Hadjar',      acronym: 'HAD', team: 'Red Bull Racing', team_colour: '#3671C6', time: '1:33.054', gap: '+1.850', dnf: false },
      { position: 13, driver_number: 5,  name: 'Gabriel Bortoleto', acronym: 'BOR', team: 'Audi',            team_colour: '#C0C0C0', time: '1:33.198', gap: '+1.994', dnf: false },
      { position: 14, driver_number: 55, name: 'Carlos Sainz',      acronym: 'SAI', team: 'Williams',        team_colour: '#64C4FF', time: '1:33.341', gap: '+2.137', dnf: false },
      { position: 15, driver_number: 23, name: 'Alex Albon',        acronym: 'ALB', team: 'Williams',        team_colour: '#64C4FF', time: '1:33.484', gap: '+2.280', dnf: false },
      { position: 16, driver_number: 14, name: 'Fernando Alonso',   acronym: 'ALO', team: 'Aston Martin',    team_colour: '#358C75', time: '1:33.621', gap: '+2.417', dnf: false },
      { position: 17, driver_number: 27, name: 'Nico Hülkenberg',   acronym: 'HUL', team: 'Audi',            team_colour: '#C0C0C0', time: '1:33.758', gap: '+2.554', dnf: false },
      { position: 18, driver_number: 7,  name: 'Arvid Lindblad',    acronym: 'LIN', team: 'Racing Bulls',    team_colour: '#6692FF', time: '1:33.901', gap: '+2.697', dnf: false },
      { position: 19, driver_number: 31, name: 'Esteban Ocon',      acronym: 'OCO', team: 'Haas',            team_colour: '#B6BABD', time: '1:34.044', gap: '+2.840', dnf: false },
      { position: 20, driver_number: 18, name: 'Lance Stroll',      acronym: 'STR', team: 'Aston Martin',    team_colour: '#358C75', time: '1:34.187', gap: '+2.983', dnf: false },
      { position: 21, driver_number: 77, name: 'Valtteri Bottas',   acronym: 'BOT', team: 'Cadillac',        team_colour: '#CC0000', time: '1:34.330', gap: '+3.126', dnf: false },
      { position: 22, driver_number: 11, name: 'Sergio Pérez',      acronym: 'PER', team: 'Cadillac',        team_colour: '#CC0000', time: '1:34.471', gap: '+3.267', dnf: false },
    ],
  },
}
