export interface Session {
  name: string
  date: string
  timeUTC: string
  timeLocal: string
  completed: boolean
}

export interface Race {
  round: number
  name: string
  shortName: string
  circuit: string
  country: string
  flag: string
  isSprint: boolean
  sessions: Session[]
}

export const CURRENT_RACE: Race = {
  round: 3,
  name: 'Japanese Grand Prix',
  shortName: 'Japan',
  circuit: 'Suzuka Circuit',
  country: 'Japan',
  flag: '🇯🇵',
  isSprint: false,
  sessions: [
    { name: 'Practice 1',  date: 'Fri 27 Mar', timeUTC: '02:30 UTC', timeLocal: '11:30 JST', completed: false },
    { name: 'Practice 2',  date: 'Fri 27 Mar', timeUTC: '06:00 UTC', timeLocal: '15:00 JST', completed: false },
    { name: 'Practice 3',  date: 'Sat 28 Mar', timeUTC: '02:30 UTC', timeLocal: '11:30 JST', completed: false },
    { name: 'Qualifying',  date: 'Sat 28 Mar', timeUTC: '06:00 UTC', timeLocal: '15:00 JST', completed: false },
    { name: 'Race',        date: 'Sun 29 Mar', timeUTC: '05:00 UTC', timeLocal: '14:00 JST', completed: false },
  ],
}

export const SEASON_CALENDAR: {
  round: number
  name: string
  flag: string
  country: string
  circuit: string
  date: string
  dateRange: string
  sprint: boolean
  completed: boolean
  calledOff: boolean
  meeting_key?: number
}[] = [
  {
    round: 1,
    name: 'Australia',
    flag: '🇦🇺',
    country: 'Australia',
    circuit: 'Albert Park Circuit',
    date: '16 Mar',
    dateRange: '13–16 Mar',
    sprint: false,
    completed: true,
    calledOff: false,
    meeting_key: 1263,
  },
  {
    round: 2,
    name: 'China',
    flag: '🇨🇳',
    country: 'China',
    circuit: 'Shanghai International Circuit',
    date: '23 Mar',
    dateRange: '13–15 Mar',
    sprint: true,
    completed: true,
    calledOff: false,
    meeting_key: 1264,
  },
  {
    round: 3,
    name: 'Japan',
    flag: '🇯🇵',
    country: 'Japan',
    circuit: 'Suzuka Circuit',
    date: '29 Mar',
    dateRange: '27–29 Mar',
    sprint: false,
    completed: false,
    calledOff: false,
  },
  {
    round: 4,
    name: 'Bahrain',
    flag: '🇧🇭',
    country: 'Bahrain',
    circuit: 'Bahrain International Circuit',
    date: '12 Apr',
    dateRange: '10–12 Apr',
    sprint: false,
    completed: false,
    calledOff: true,
  },
  {
    round: 5,
    name: 'Saudi Arabia',
    flag: '🇸🇦',
    country: 'Saudi Arabia',
    circuit: 'Jeddah Corniche Circuit',
    date: '19 Apr',
    dateRange: '17–19 Apr',
    sprint: false,
    completed: false,
    calledOff: true,
  },
  {
    round: 6,
    name: 'Miami',
    flag: '🇺🇸',
    country: 'United States',
    circuit: 'Miami International Autodrome',
    date: '3 May',
    dateRange: '1–3 May',
    sprint: true,
    completed: false,
    calledOff: false,
  },
  {
    round: 7,
    name: 'Canada',
    flag: '🇨🇦',
    country: 'Canada',
    circuit: 'Circuit Gilles Villeneuve',
    date: '24 May',
    dateRange: '22–24 May',
    sprint: true,
    completed: false,
    calledOff: false,
  },
  {
    round: 8,
    name: 'Monaco',
    flag: '🇲🇨',
    country: 'Monaco',
    circuit: 'Circuit de Monaco',
    date: '7 Jun',
    dateRange: '5–7 Jun',
    sprint: false,
    completed: false,
    calledOff: false,
  },
  {
    round: 9,
    name: 'Barcelona-Catalunya',
    flag: '🇪🇸',
    country: 'Spain',
    circuit: 'Circuit de Barcelona-Catalunya',
    date: '14 Jun',
    dateRange: '12–14 Jun',
    sprint: false,
    completed: false,
    calledOff: false,
  },
  {
    round: 10,
    name: 'Austria',
    flag: '🇦🇹',
    country: 'Austria',
    circuit: 'Red Bull Ring',
    date: '28 Jun',
    dateRange: '26–28 Jun',
    sprint: false,
    completed: false,
    calledOff: false,
  },
  {
    round: 11,
    name: 'Britain',
    flag: '🇬🇧',
    country: 'Great Britain',
    circuit: 'Silverstone Circuit',
    date: '5 Jul',
    dateRange: '3–5 Jul',
    sprint: true,
    completed: false,
    calledOff: false,
  },
  {
    round: 12,
    name: 'Belgium',
    flag: '🇧🇪',
    country: 'Belgium',
    circuit: 'Circuit de Spa-Francorchamps',
    date: '19 Jul',
    dateRange: '17–19 Jul',
    sprint: false,
    completed: false,
    calledOff: false,
  },
  {
    round: 13,
    name: 'Hungary',
    flag: '🇭🇺',
    country: 'Hungary',
    circuit: 'Hungaroring',
    date: '26 Jul',
    dateRange: '24–26 Jul',
    sprint: false,
    completed: false,
    calledOff: false,
  },
  {
    round: 14,
    name: 'Netherlands',
    flag: '🇳🇱',
    country: 'Netherlands',
    circuit: 'Circuit Zandvoort',
    date: '23 Aug',
    dateRange: '21–23 Aug',
    sprint: true,
    completed: false,
    calledOff: false,
  },
  {
    round: 15,
    name: 'Italy',
    flag: '🇮🇹',
    country: 'Italy',
    circuit: 'Autodromo Nazionale Monza',
    date: '6 Sep',
    dateRange: '4–6 Sep',
    sprint: false,
    completed: false,
    calledOff: false,
  },
  {
    round: 16,
    name: 'Madrid',
    flag: '🇪🇸',
    country: 'Spain',
    circuit: 'Madrid Street Circuit',
    date: '13 Sep',
    dateRange: '11–13 Sep',
    sprint: false,
    completed: false,
    calledOff: false,
  },
  {
    round: 17,
    name: 'Azerbaijan',
    flag: '🇦🇿',
    country: 'Azerbaijan',
    circuit: 'Baku City Circuit',
    date: '26 Sep',
    dateRange: '26 Sep',
    sprint: false,
    completed: false,
    calledOff: false,
  },
  {
    round: 18,
    name: 'Singapore',
    flag: '🇸🇬',
    country: 'Singapore',
    circuit: 'Marina Bay Street Circuit',
    date: '11 Oct',
    dateRange: '9–11 Oct',
    sprint: true,
    completed: false,
    calledOff: false,
  },
  {
    round: 19,
    name: 'United States',
    flag: '🇺🇸',
    country: 'United States',
    circuit: 'Circuit of the Americas',
    date: '25 Oct',
    dateRange: '23–25 Oct',
    sprint: false,
    completed: false,
    calledOff: false,
  },
  {
    round: 20,
    name: 'Mexico',
    flag: '🇲🇽',
    country: 'Mexico',
    circuit: 'Autodromo Hermanos Rodriguez',
    date: '1 Nov',
    dateRange: '30 Oct–1 Nov',
    sprint: false,
    completed: false,
    calledOff: false,
  },
  {
    round: 21,
    name: 'Brazil',
    flag: '🇧🇷',
    country: 'Brazil',
    circuit: 'Autodromo Jose Carlos Pace',
    date: '8 Nov',
    dateRange: '6–8 Nov',
    sprint: false,
    completed: false,
    calledOff: false,
  },
  {
    round: 22,
    name: 'Las Vegas',
    flag: '🇺🇸',
    country: 'United States',
    circuit: 'Las Vegas Strip Circuit',
    date: '21 Nov',
    dateRange: '19–21 Nov',
    sprint: false,
    completed: false,
    calledOff: false,
  },
  {
    round: 23,
    name: 'Qatar',
    flag: '🇶🇦',
    country: 'Qatar',
    circuit: 'Lusail International Circuit',
    date: '29 Nov',
    dateRange: '27–29 Nov',
    sprint: false,
    completed: false,
    calledOff: false,
  },
  {
    round: 24,
    name: 'Abu Dhabi',
    flag: '🇦🇪',
    country: 'United Arab Emirates',
    circuit: 'Yas Marina Circuit',
    date: '6 Dec',
    dateRange: '4–6 Dec',
    sprint: false,
    completed: false,
    calledOff: false,
  },
]
